[toolchain]
channel = "nightly-2025-02-20" # "nightly-2024-12-10"
# channel = "stage1"
components = [
    "rust-src",
    "rustc-dev",
    "llvm-tools-preview",
    "rust-analyzer",
    "clippy",
    "miri"
]
